import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'src/app.dart';
import 'src/features/transactions/domain/transaction_model.dart';
import 'src/features/transactions/data/wallet_repository.dart';
import 'src/core/services/notification_service.dart';
import 'src/features/bnpl/domain/bnpl_model.dart';
import 'src/features/bnpl/data/bnpl_repository.dart';
import 'src/features/rewards/domain/reward_model.dart';
import 'src/features/notifications/domain/notification_preferences.dart';
import 'src/features/rewards/data/rewards_repository.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  try {
    if (kIsWeb) {
      await Firebase.initializeApp(
        options: const FirebaseOptions(
          apiKey: 'AIzaSyBdo-nXmSOdX2kqUAXL1U8DG3Cq3gbghkA',
          appId: '1:1001141776954:web:9782a3b1dccad96ea57b03',
          messagingSenderId: '1001141776954',
          projectId: 'cred-money-1d9a7',
          authDomain: 'cred-money-1d9a7.firebaseapp.com',
          storageBucket: 'cred-money-1d9a7.firebasestorage.app',
        ),
      );
    } else {
      await Firebase.initializeApp();
    }
  } catch (e) {
    debugPrint('Firebase initialization failed: $e');
  }

  // Initialize Hive
  await Hive.initFlutter();

  // Register Hive Adapters
  // NOTE: These adapters are generated by 'dart run build_runner build'.
  // We register them here assuming the code is generated.
  // Hive.registerAdapter(TransactionAdapter());
  // Hive.registerAdapter(TransactionTypeAdapter());

  // Initialize Wallet Box
  final walletRepo = WalletRepository();
  await walletRepo.init();

  // Register BNPL Adapter
  Hive.registerAdapter(BnplTransactionAdapter());

  // Initialize BNPL Box
  final bnplRepo = BnplRepository();
  await bnplRepo.init();

  // Register Rewards Adapter
  Hive.registerAdapter(RewardTransactionAdapter());

  // Initialize Rewards Box
  final rewardsRepo = RewardsRepository();
  await rewardsRepo.init();

  // Register Transaction Category Adapter
  // Hive.registerAdapter(TransactionCategoryAdapter()); // Generated by build_runner
  Hive.registerAdapter(NotificationPreferencesAdapter());

  // Initialize Notification Service
  final notificationService = NotificationService();
  await notificationService.init();

  // Open preferences box
  await Hive.openBox<NotificationPreferences>('preferences_box');

  runApp(
    ProviderScope(
      overrides: [
        // Override providers if necessary, or just rely on default
      ],
      child: const SmartFinanceApp(),
    ),
  );
}
